### ISSUE TITLE
SingleInstanceCheck

### ISSUE THREAD

**Issue by KoneK1** [RolandMueller1994/UltSigPro#39]
Die Klasse SingleInstanceCheck überprüft, ob UltSigPro bereits läuft und somit eine zweite Instanz gestartet wurde. Dazu wird bei jedem Start von UltSigPro ein Thread (SingleInstanceThread) erstellt, der einen ServerSocket erstellt und auf eine Verbindung über einen bestimmten Port wartet. Die Verbindung kommt dabei nur zu Stande, falls eine zweite Instanz von UltSigPro gestartet wird, da hier erneut ein ServerSocket gestartet wird und über den gleichen Port eine Kommunikation stattfindet.

Falls hier nun die zweite Instanz feststellt, dass UltSigPro bereits läuft, soll dem User eine Fehlermeldung mit Hilfe der Klassen SecondInstanceGui & SecondInstanceDialog angezeigt werden.  Das erkennen, ob UltSigPro bereits läuft, funktioniert. Das mit der GUI funktioniert noch nicht. Hier fliegt, sobald eine neue GUI gebaut werden soll (SingleInstanceCheck Z. 44/45), eine Exception aufgrund des doppelten "launch"-Aufrufs. 
![image](https://user-images.githubusercontent.com/29126123/34386181-ba775c48-eb27-11e7-9db0-d2aa525e22ef.png)

**Comment by RolandMueller1994** [comment]
Es wurde zwei mal eine launch-Methode aufgerufen. Einmal in USPGui und in SecondInstanceGui. Das ist mit FX nicht möglich. Außerdem kann eine Klasse, welche von Application erbt, nicht als innere Klasse ausgeführt werden.
